### PR TITLE
Run `brew update` also if homebrew is already installed

### LINKED ISSUE #11: Run `brew update` also if homebrew is already installed
Dependencies installed through https://github.com/Homebrew/homebrew-bundle (e.g. via a _Brewfile_) will then automatically be upgraded.

### PR DESCRIPTION
**Pull request by mbode**
closes #11

### CODE REVIEW

**Comment by d12frosted** [comment]
Hey, thank you for your PR.

Correct me if I am wrong, but it seems that the issue you have opened is about **upgrading** packages. If so, `brew update` is not what you want as it just 'updates the formulas'. What you want is `brew upgrade`. 

- `brew update` is run automatically by brew on various commands (and can be configured), so I think that `dotbot-brew` should not interfere with user configuration.
- IMHO, `brew upgrade` doesn't sound like a good default. You execute `install` script when running `dotbot`, not `upgrade`. 

What do you think?

**Comment by mbode** [comment]
There are several points here I think:
* You are right, I like to call `install` regularly to upgrade my installed packages but maybe that's just me. I am using [brew-bundle](https://github.com/Homebrew/homebrew-bundle) (with dotbot-brew's `brewfile` directive), whose behavior is to upgrade packages if an upgrade is available (cf. https://github.com/Homebrew/homebrew-bundle#install-1). For this to happen, there needs to be a `brew update` before.
* I did not know about the configurability, this might solve my issue as well. Do you happen to know how I can configure `brew bundle` to run `brew update` automatically?
* Still, one might consider it slightly inconsistent that homebrew (together with the formulas) is updated to the newest versions when installing homebrew but not if there is an existing installation. If installing dotfiles on a new machine with an old homebrew installation present, I'd prefer it to be updated before further stuff happens.

**Comment by d12frosted** [comment]
Ok. I didn't know that `brew bundle` upgrades installed formulas. But you still need to call `brew update`, right?

**Comment by mbode** [comment]
Well, in the submitted change this happens automatically in `_bootstrap_brew` so you do not have to call it yourself.

**Comment by d12frosted** [comment]
ok, there are some inconsistencies in brew behaviour here, but I agree that it would not hurt updating packages before installing anything.

thanks

**Pull request merged**
