### PR TITLE
Use --verbose command in brewfile directive

### LINKED ISSUE #19: Use "brew bundle --verbose" for brewfile directives
`brew bundle` shows prettified output with green colors after installing a package and no styling in case of the package being already installed, so it looks great.

`brew bundle --verbose` shows more details on what is actually going on, in particular on whether a particular package is being installed. 

the non-verbose version is prettier but it looks like it's stuck or something on large installs. It doesn't show enough information.

Consider changing this?

### PR DESCRIPTION
**Pull request by miguelandres**
Proposing this PR as a solution to my bug #19 

Fixes #19

### CODE REVIEW

**Review by d12frosted — APPROVED** [review]
LGTM. I will merge it soon.

**Comment by d12frosted** [comment]
FYI, there are issues with CI, let me fix them before I merge this PR. I will review your other PR afterwards. Sorry for delays.

**Comment by d12frosted** [comment]
I've fixed the issues in https://github.com/d12frosted/dotbot-brew/pull/23. There was more than 1 issue. Please update your branch, so I can merge it 😸

**Comment by miguelandres** [comment]
Let's handle this on the newer PRs

**Pull request closed without merging**
